### PR TITLE
Update Infinispan to 13.0.0.CR2

### PR DESCRIPTION
**Pull request by pruivo**

### CODE REVIEW

**Review by oraNod — APPROVED** [review]
LGTM @pruivo I'll merge today. Should we move those version numbers into a variable somewhere?

**Comment by pruivo** [comment]
@oraNod do you mean the docs? it would be perfect if it could fetch from the properties in the pom.xml

**Comment by oraNod** [comment]
> @oraNod do you mean the docs? it would be perfect if it could fetch from the properties in the pom.xml

@pruivo Yeah, that's what I meant. I started looking into adding a pom.xml to the documentation directory but it's trickier than I thought. Also the way the docs get built on the community site mean that the attributes need to be defined somewhere in the asciidoc, so we can't move them to pom.xml.

**Comment by karesti** [comment]
@pruivo are the tutorials working ?

**Comment by pruivo** [comment]
the CI is green, so I think so.

**Review by karesti — APPROVED** [review]

**Pull request merged**
