### PR TITLE
Update to Infinispan 9.2.0.CR1 and some leftover work ISPN-8024

### PR DESCRIPTION
**Pull request by galderz**

### CODE REVIEW

**Comment by galderz** [comment]
This requires this [docker image PR](https://github.com/jboss-dockerfiles/infinispan/pull/79) to be integrated so that we can verify the docker image stuff works fine.

**Comment by galderz** [comment]
The docker image PR has been integrated but I see an [error](https://gist.github.com/galderz/1f8cdac42feda77f2a710be2d1fa334b) with Spark simple tutorial. Checking with @gustavonalle to see what's up with that.

**Comment by gustavonalle** [comment]
@galderz I can't build the project:

```
[ERROR]   The project org.infinispan.tutorial.simple:infinispan-simple-tutorials-hibernate-cache-spring-local:1.0.0-SNAPSHOT (/home/gfernandes/github/infinispan-simple-tutorials/hibernate-cache/spring-local/pom.xml) has 1 error
[ERROR]     Non-resolvable parent POM for org.infinispan.tutorial.simple:infinispan-simple-tutorials-hibernate-cache-spring-local:1.0.0-SNAPSHOT: Could not find artifact org.springframework.boot:spring-boot-starter-parent:pom:2.0.0.M7 in spring-releases (https://repo.spring.io/libs-release) and 'parent.relativePath' points at wrong local POM @ line 12, column 12 -> [Help 2]
```

**Comment by gustavonalle** [comment]
@galderz Do I need a special repo to resolve ```org.springframework.boot:spring-boot-starter-parent:pom:2.0.0.M7```?

**Comment by gustavonalle** [comment]
@galderz https://github.com/infinispan/infinispan-simple-tutorials/pull/37 should fix the spark demo and 
https://github.com/infinispan/infinispan-simple-tutorials/pull/36 added CI to this repo. 
We only need to figure out the broken dependency above

**Comment by galderz** [comment]
@gustavonalle I don't recall any special for Spring, let me clear my local Spring artifacts and try again.

**Comment by gustavonalle** [comment]
FYI, CI failed with the same error: https://travis-ci.org/infinispan/infinispan-simple-tutorials/builds/332689080?utm_source=github_status&utm_medium=notification

**Comment by galderz** [comment]
I've cleared org.springframework from my local repo and then did `mvn clean package exec:exec` in `hibernate-cache/spring-local` and it worked fine. The pom.xml in the example adds repositories required for this.

**Comment by galderz** [comment]
https://gist.github.com/galderz/01e82c1c8d90a91ac578d0849c6ffa31

**Comment by galderz** [comment]
I'm looking into this further

**Comment by gustavonalle** [comment]
Works for me now, thanks @galderz !

**Pull request merged**
