### PR TITLE
Fixing build and code to be able to compile with latest CPP Infinispan client on RHEL and Fedora

### PR DESCRIPTION
**Pull request by dmvolod**
Now build is working fine on both platforms

### CODE REVIEW

**Comment by karesti** [comment]
@rigazilla if you have time to look this PR 😄

**Comment by rigazilla** [comment]
Hi @dmvolod
Which RHEL and Fedora version you used?
Did you used the client rpms from infinispan.org?

I'm asking this because I would like to update the tutorial with the steps for a docker run, so the user can start from a clean install.
Thanks for contributing!

and thanks @karesti for the heads-up :)

**Comment by dmvolod** [comment]
Thanks for response, @rigazilla !

I've tried with Fedora 30 and self-build cpp-client from https://github.com/infinispan/cpp-client/ master branch as well as RHEL 7.7 (Maipo) with jdg-cpp-client.x86_64 from Red Hat repository.

I also find some issues building cpp-client on Fedora, as it package some protobuf libraries inside rpm, call it ..RHEL..rpm and conflicts with installed protobuf-c-compiler package. I could separate RHEL and Fedora or any other Linux install with cmake file and fix it if community will accept this changes.

**Comment by rigazilla** [comment]
> Thanks for response, @rigazilla !
> 
> I've tried with Fedora 30 and self-build cpp-client from https://github.com/infinispan/cpp-client/ master branch as well as RHEL 7.7 (Maipo) with jdg-cpp-client.x86_64 from Red Hat repository.
> 
Perfect, if it's ok for you I'll add a commit on top of your PR with the docker steps for centos 7 (rpms are for that release, IIRC)

> I also find some issues building cpp-client on Fedora, as it package some protobuf libraries inside rpm, call it ..RHEL..rpm and conflicts with installed protobuf-c-compiler package. I could separate RHEL and Fedora or any other Linux install with cmake file and fix it if community will accept this changes.

This issue is more complex: the project CMakeLists.txt has a long history and really needs a clean up. Unfortunately I haven't much time now for this and I can't merge anything there in a short time unless it is a very simple PR. But please, if you already have developed something interesting please leave it in a PR, I'll have a look when possible.

Specific to protobuf lib: it's definitely uncommon to have it packaged in the client rpm and it should be removed. I can't remember why we had to do that... if that fix something, we should find a different solution

**Comment by dmvolod** [comment]
> This issue is more complex: the project CMakeLists.txt has a long history and really needs a clean up. Unfortunately I haven't much time now for this and I can't merge anything there in a short time unless it is a very simple PR. But please, if you already have developed something interesting please leave it in a PR, I'll have a look when possible.
>
I can try to start clearing CMakeLists.txt to get it better and align it with project build. Also can try to add support for different linux versions and try to build with several os versions (both linux and windows). 

> Specific to protobuf lib: it's definitely uncommon to have it packaged in the client rpm and it should be removed. I can't remember why we had to do that... if that fix something, we should find a different solution
>
I will check with depended rpm's or check another linking options for both RHEL and Fedora.
Also I didn't build with Fedora 31 and this need to be checked.
Also looks like need to be checked required for build and test rpm's like krb5-workstation and any other libraries (I saw it in Docker file and looks like can be copy in build process).

**Comment by rigazilla** [comment]
I've added a docker run to this PR and small changes to @dmvolod fixes.
Someone is interested in trying the docker tutorial? Should be quite easy....
@dmvolod , @karesti  or @oraNod

**Comment by rigazilla** [comment]
@dmvolod I've added some notes as starting point on what I think we need to do on the build process here: https://github.com/infinispan/cpp-client/issues/358
Please, take it as draft

**Comment by rigazilla** [comment]
merged thanks @dmvolod !

**Pull request merged**
