### PR TITLE
ISPN-10375 asciidoc simple tutorials

### PR DESCRIPTION
**Pull request by oraNod**
https://issues.jboss.org/browse/ISPN-10375

### CODE REVIEW

**Comment by oraNod** [comment]
@tristantarrant and @galderz this PR adds RHDG productization for tutorial docs. I've made changes to the Operator, C++, C#, and Streams tutorials to get started. as we move closer to release, we can productize and create other tutorials using the asciidoc templates I've added. 

Note that changes to the community site depend on this PR. I have a separate PR for infinispan.org/tutorials at: https://github.com/infinispan/infinispan.github.io/pull/78

**Comment by karesti** [comment]
@oraNod could you rebase master to pass the build, please?

**Comment by oraNod** [comment]
@karesti rebased. thanks!

**Comment by oraNod** [comment]
Closing as out of date. Will start a new PR instead of reworking this one.

**Pull request closed without merging**
