### PR TITLE
move main for 15

### PR DESCRIPTION
**Pull request by karesti**

### CODE REVIEW

**Review by ryanemerson — APPROVED** [review]

**Comment by pruivo** [comment]
@karesti it does not compile. Maybe update to the latest 15?

**Comment by karesti** [comment]
@pruivo sorry, dependency naming changes

**Comment by pruivo** [comment]
Protostream changes are required as well :cry:

**Review by pruivo — APPROVED** [review]
Didn't run all the tutorials but it looks good to me :+1:

**Comment by pruivo** [comment]
merged! thanks  @karesti !

**Pull request merged**
