### PR TITLE
HRCPP-307 Fixed errors

### LINKED ISSUE #14: C# Tutorial doesn't work
The Simple.cs has too many bugs in it and it wouldn't build in VS 2015.

### PR DESCRIPTION
**Pull request by rigazilla**
Fixed some error, added readme and removed x86 configuration (only 64 bit now)
This fixes #14

### CODE REVIEW

**Comment by rigazilla** [comment]
@vchintal I've extended the readme with the instructions on how to change the csproj so if the user prefers to point it's installation directory, instead of copying the dll, knows how to do.

**Comment by rigazilla** [comment]
The example is still not complete, I probably need to add the SSL libraries

**Comment by rigazilla** [comment]
Now the tutorial should without changing the user env settings

**Comment by rigazilla** [comment]
@slaskawi thanks for the review. @vchintal wdyta, can we integrate?

**Comment by slaskawi** [comment]
Integrated thanks!

**Pull request merged**
