### PR TITLE
Add CI

### PR DESCRIPTION
**Pull request by gustavonalle**

### CODE REVIEW

**Comment by galderz** [comment]
This won't work, we need Infinispan Server instances and Wildfly instances up and running to get this to work. Besides, we can't currently have both Infinispan Server and Wildfly instances up in localhost at same time since they'd have bind issues.

Ideally we want to move all examples to relying on docker images to get CI to work reliably?

**Comment by gustavonalle** [comment]
I can remove the testAll.sh script and let it just build the project for now, WDYT?

**Comment by gustavonalle** [comment]
Now it should at least verify that the project builds until https://github.com/infinispan/infinispan-simple-tutorials/issues/38

**Comment by gustavonalle** [comment]
Build is green!

**Pull request merged**
