### PR TITLE
add a cluster switch example in java

### PR DESCRIPTION
**Pull request by karesti**
Java example with switch cluster

### CODE REVIEW

**Comment by karesti** [comment]
This is ready for merge

**Comment by pruivo** [comment]
Module `<module>infinispan-remote/cross-site-replication</module>` should be added to the parent `pom.xml`

**Comment by pruivo** [comment]
I would add some output to the tutorial since we see nothing in the terminal. My suggestion follows:

```java
   public static void main(String[] args) {
      ConfigurationBuilder builder = TutorialsConnectorHelper.connectionConfig();
      builder.addCluster("NYC").addClusterNodes("127.0.0.1:31223");

      try (RemoteCacheManager client = TutorialsConnectorHelper.connect(builder)) {
         RemoteCache<String, String> cache = client.getCache("xsiteCache");
         cache.put("hello", "world");
         printCluster("LON", cache);
         System.out.println("hello " + cache.get("hello") + " from LON");
         client.switchToCluster("NYC");
         printCluster("NYC", cache);
         System.out.println("hello " + cache.get("hello") + " from NYC");
         cache.put("hello-nyc", "world");

         client.switchToDefaultCluster();
         printCluster("LON", cache);
         // Connecting to NYC http://localhost:31222/console/cache/xsiteCache
         // hello (copied from LON) and hello-nyc exist
      }
   }

   private static void printCluster(String clusterName, RemoteCache<?,?> cache) {
      System.out.println(clusterName + " members: " + cache.getCacheTopologyInfo().getSegmentsPerServer().keySet().stream().map(Object::toString).collect(Collectors.joining(",")));
   }
```

prints:

```
[INFO] --- exec:1.6.0:exec (default-cli) @ infinispan-simple-tutorials-remote-cross-site ---
[INFO] [stdout] LON members: 127.0.0.1/<unresolved>:11222
[INFO] [stdout] hello world from LON
[INFO] [stdout] NYC members: 127.0.0.1/<unresolved>:31223
[INFO] [stdout] hello world from NYC
[INFO] [stdout] LON members: 127.0.0.1/<unresolved>:11222
```

just my 2cents :+1:

**Comment by karesti** [comment]
@pruivo done

**Comment by karesti** [comment]
rebased

**Comment by pruivo** [comment]
merged! thanks @karesti !

**Pull request merged**
