### PR TITLE
Ispn 7305/spring session tutorial

### PR DESCRIPTION
**Pull request by slaskawi**
https://issues.jboss.org/browse/ISPN-7305

### CODE REVIEW

**Comment by gustavonalle** [comment]
@slaskawi Also here, we need to able to execute via "mvn exec:exec"

**Comment by slaskawi** [comment]
@gustavonalle Added `README.md`

**Comment by gustavonalle** [comment]
LGTM, since you put ```9.0.0.Beta2```, better to wait to integrate?

**Comment by slaskawi** [comment]
@gustavonalle Unfortunately we can not upgrade to `Beta1` because of this bug: https://github.com/infinispan/infinispan/pull/4718

So let's wait till `Beta2` and then integrate it.

**Comment by galderz** [comment]
Looks good, integrating

**Pull request merged**
