### PR TITLE
Upgraded F8 Maven plugin in Kubernetes tutorial

### PR DESCRIPTION
**Pull request by slaskawi**

### CODE REVIEW

**Comment by slaskawi** [comment]
@galderz Fixed.

Now the logs that you see really depend on scheduling on your box. For testing things like this I usually do:
* Scale its DeploymentConfig to 0 - `oc scale dc/infinispan-simple-tutorials-kubernetes --replicas=0`
* Scale it to 3 - `oc scale dc/infinispan-simple-tutorials-kubernetes --replicas=0`
* Watch logs using [kubetail](https://github.com/johanhaleby/kubetail) - `kubetail --selector app=infinispan-simple-tutorials-kubernetes`

On my box I can see logs from 3 containers running with the same view:

```
INFO: ISPN000094: Received new cluster view for channel ISPN: [infinispan-simple-tutorials-kubernetes-2-4z8db-23841|2] (3) [infinispan-simple-tutorials-kubernetes-2-4z8db-23841, infinispan-simple-tutorials-kubernetes-2-x7scq-64964, infinispan-simple-tutorials-kubernetes-2-fs45f-50583]
```
So everything should be fine...

**Comment by galderz** [comment]
@slaskawi Did you reply to my other comment?

> Also, I noticed that the README still says that we need to add additional privileges to the account for this to work. Why is that needed? I've created Infinispan Server clusters in OpenShift in myproject without the need for this.

**Comment by galderz** [comment]
Can you add `-Dfabric8.openshift.trimImageInContainerSpec=true` as property within pom.xml? That way the redeployment workaround kicks in without the user having to add it manually in command line. E.g.

```
  <properties>
...
<fabric8.openshift.trimImageInContainerSpec>true</fabric8.openshift.trimImageInContainerSpec>
...
  </properties>
```

**Comment by galderz** [comment]
This is not working right yet (see [here](https://gist.github.com/galderz/72d97f0ee8c533f182764776520812f1)). 

The cluster does indeed form of 3 nodes, but the output does not seem to match what you'd expect to happen. Each node updates its own entry in the cache and each node adds a listener. No matter what the distribution of the data is, 3 updates should result in 3 listener calls given that the listeners are local. Even if the 3 updates happen in a single node due to data distribution, each update should appear be visible in the listener output. Right now you only seem to get 2 updates appearing and that doesn't make sense.

**Comment by galderz** [comment]
Also, the tutorial needs updating to [avoid using default cache](https://github.com/infinispan/infinispan-simple-tutorials/blob/master/kubernetes/src/main/java/org/infinispan/tutorial/simple/kubernetes/InfinispanKubernetes.java#L39). Otherwise you see warning messages in the tutorial like this:

{code}
[INFO] F8: Mar 06, 2018 5:34:27 PM org.infinispan.manager.DefaultCacheManager <init>
[INFO] F8: WARN: ISPN000435: Cache manager initialized with a default cache configuration but without a name for it. Set it in the GlobalConfiguration.
{code}

**Comment by slaskawi** [comment]
> Also, I noticed that the README still says that we need to add additional privileges to the account for this to work. Why is that needed? I've created Infinispan Server clusters in OpenShift in myproject without the need for this.

Yes, it is needed. Local cluster will always work because everything is... local ;) Infinispan uses `KUBE_PING` which requires those permissions.

**Comment by slaskawi** [comment]
> The cluster does indeed form of 3 nodes, but the output does not seem to match what you'd expect to happen. Each node updates its own entry in the cache and each node adds a listener. No matter what the distribution of the data is, 3 updates should result in 3 listener calls given that the listeners are local. Even if the 3 updates happen in a single node due to data distribution, each update should appear be visible in the listener output. Right now you only seem to get 2 updates appearing and that doesn't make sense.

+1, I'll remove those listeners... they only blur the functionality I want to show... I'll do something simpler

**Comment by slaskawi** [comment]
@galderz Updated... waiting for the next round of review

**Pull request merged**
