### PR TITLE
ISPN-8804 Simple tutorial clustered lock

### PR DESCRIPTION
**Pull request by karesti**
https://issues.jboss.org/browse/ISPN-8804

### CODE REVIEW

**Comment by wburns** [comment]
I wonder if we shouldn't worry about multiple nodes for this simple tutorial. I don't think any other tutorials setup a cluster of nodes. And tbh if we do we should make sure to have a consistent way to do it between all the various tutorials.

**Comment by karesti** [comment]
@wburns ok, I will simplify it

**Comment by karesti** [comment]
@galderz I believed I had 3 cache managers instead of 1. I'm going to check this better, thank you !

**Comment by galderz** [comment]
Indeed, I think @wburns is right. The other cluster tutorials start just one node.

**Comment by karesti** [comment]
@wburns @galderz I modified the quickstart using a single cluster manager

**Comment by karesti** [comment]
@wburns rebased !

**Comment by wburns** [comment]
Integrated, thanks @karesti !

**Pull request merged**
