### PR TITLE
ISPN-15708 Refactor Infinispan Embedded Kubernetes tutorial

### PR DESCRIPTION
**Pull request by ryanemerson**
https://issues.redhat.com/browse/ISPN-15708

### CODE REVIEW

**Comment by karesti** [comment]
@ryanemerson https://github.com/infinispan/infinispan-simple-tutorials/tree/main/documentation/asciidoc

**Comment by ryanemerson** [comment]
@karesti How do you want the .adoc to be integrated in the embedded section? Currently this section is just a table with a summary and a link to the tutorial location on GitHub which will display the README.adoc if present.

https://infinispan.org/tutorials/simple/simple_tutorials.html#embedded-tutorials_embedded-cache-tutorials

**Comment by karesti** [comment]
the other tutorials embedding don't have any doc. I would add a section under the embedding tutorial with the content of this one with a "Kubernetes" title and pointing to the tutorial

**Comment by karesti** [comment]
[1.2. Kubernetes] section or another title. I can move it in another PR if you want

**Review by karesti — APPROVED** [review]

**Comment by manusa** [comment]
Awesome, thank you folks!

**Pull request merged**
