### PR TITLE
Update fabric8-maven-plugin to 4.4.2

### PR DESCRIPTION
**Pull request by ryanemerson**

### CODE REVIEW

**Comment by pruivo** [comment]
merged! thanks @ryanemerson !

**Comment by manusa** [comment]
Hi folks, any chance we can work on migrating from [Fabric8 Maven Plugin](https://github.com/fabric8io/fabric8-maven-plugin/#deprecation-note) to [Eclipse JKube](https://github.com/eclipse/jkube)?

**Comment by karesti** [comment]
@manusa @ryanemerson if so, would you like to contribute ?

**Comment by manusa** [comment]
I'm happy to help if I can.

**Comment by karesti** [comment]
I'll wait to @ryanemerson to answer

**Comment by ryanemerson** [comment]
I need to rework this quickstart already, so when I do this I'll handle the migration to JKube.

**Comment by manusa** [comment]
> I need to rework this quickstart already, so when I do this I'll handle the migration to JKube.

Awesome, thanks. If you need any help regarding the JKube side, don't hesitate to reach out.

**Comment by karesti** [comment]
@ryanemerson may I log a jira ?

**Pull request merged**
